<a href="https://colab.research.google.com/github/priyanhsu10/linearAlgebra/blob/main/matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
v=np.array([1,2,3])
w=np.array([3,4,4])
print(v-w)

[-2 -2 -1]


In [3]:
print(3*v)

[3 6 9]


In [4]:
print(np.linalg.norm(v))

3.7416573867739413


In [5]:
print(v.dot(w))

23


In [8]:
p= np.array([[1,7], [2,1],[3,2]])
q=np.array([[1,1],[1,-1],[3,2]])
r=np.array([[1,3,1],[1,0,1]])
c2=np.dot(p,r)
print(c2)

[[8 3 8]
 [3 6 3]
 [5 9 5]]


In [9]:
det=np.linalg.det(c2)
print(det)

0.0


In [12]:
m=np.array([[1,2],[-2,1]])
print(np.linalg.inv(m))
print(np.linalg.det(m))

[[ 0.2 -0.4]
 [ 0.4  0.2]]
5.000000000000001
